### ISSUE TITLE
Falha na instalação

### ISSUE THREAD

**Issue by lucas-rabelo** [andre-gasparin/leafletadianti#1]
Olá André, eu tentei instalar seu repositório, mas sem sucesso.
Aparece uma aviso para mim que devo inserir um token. Mas não sei qual é. Você sabe me dizer como proceder daqui em diante na instalação?

**Comment by andre-gasparin** [comment]
Opa Lucas! esse erro acontece por que o GITHUB está "barrando" sua requisição,
É necessário que vc vá na sua área administrativa do git, crie um token e utilize ele no seu composer.

Não li o artigo completo, mais provavelmente isso irá te ajudar: 
https://www.previousnext.com.au/blog/managing-composer-github-access-personal-access-tokens

**Comment by lucas-rabelo** [comment]
Olá André, segui o procedimento no link que me passou, mas tive um outro problema.
Esse aviso foi mostrado no meu prompt:

"Could not find a matching version of package andregasparin/plugins. Check the package spelling, your version constr
  aint and that the package is available in a stability which matches your minimum-stability (stable)."

Como fazer?

**Comment by andre-gasparin** [comment]
na hora de adicionar o rep vc usou "composer require andregasparin/plugins @dev "? com o @dev no final?

**Comment by lucas-rabelo** [comment]
Sim, do jeito que está no Readme

**Comment by andre-gasparin** [comment]
Pode me mandar seu json do composer?
vc está em algum grupo do telegram ou whats? ai podemos ver e você só coloca a solução aqui!

**Comment by lucas-rabelo** [comment]
Posso mandar sim.

Composer.json:
`{
  "repositories": [
    { "type": "vcs", "url": "https://github.com/pablodalloglio/ole" },
    { "type": "vcs", "url": "https://github.com/pablodalloglio/spreadsheet_excel_writer" },
    { "type": "vcs", "url": "https://github.com/andre-gasparin/leafletadianti" }
  ],
    "require": {
        "phpmailer/phpmailer": "^6.0",
        "tburry/pquery": "^1.1",
        "picqer/php-barcode-generator": "^0.2.2",
        "dompdf/dompdf": "^0.8.1",
        "bacon/bacon-qr-code": "^1.0",
        "phprtflite/phprtflite": "^1.3",
        "firebase/php-jwt": "^5.0",
    "pablodalloglio/ole": "dev-master",
    "pablodalloglio/spreadsheet_excel_writer": "dev-master",
    "linfo/linfo": "^4.0",
    "phpoffice/phpspreadsheet": "^1.10",
    "nfephp-org/sped-nfe": "^5.0",
    "nfephp-org/sped-da": "^0.2.0",
    "nfephp-org/sped-cte": "dev-master"
    }
}
`

Eu não estou em nenhum grupo do whatsapp ou telegram.

**Comment by lucas-rabelo** [comment]
Problema resolvido

Era somente usar o comando "composer require andregasparin/plugins dev-main ". Obrigado André.
